=pod

=encoding UTF-8

=head1 NAME

Acme::CPANAuthors::Canadian - We are Canadian CPAN authors

=head1 VERSION

version 0.0108

=head1 DESCRIPTION

This class provides a hash of Canadian CPAN authors' PAUSE ID and name to
the C<Acme::CPANAuthors> module.

    use strict;
    use warnings;
    use Acme::CPANAuthors;

    my $authors  = Acme::CPANAuthors->new("Canadian");

    my $number   = $authors->count;
    my @ids      = $authors->id;
    my @distros  = $authors->distributions("ZOFFIX");
    my $url      = $authors->avatar_url("ZOFFIX");
    my $kwalitee = $authors->kwalitee("ZOFFIX");
    my $name     = $authors->name("ZOFFIX");

See documentation for L<Acme::CPANAuthors> for more details.

=head1 US PEOPLE

We are Canadian CPAN authors:

=over 4

=item *

Zoffix Znet

=item *

Karen Etheridge

=item *

Roman F.

=item *

Graham TerMarsch

=item *

Olaf Alders

=item *

Timothy Legge

=item *

Jeremy Stashewsky

=item *

Luke Closs

=item *

Kevin Jones

=item *

Mike Smith

=back

=head1 MAINTENANCE

If you are a Canadian CPAN author not listed here, please send me your ID/name
via RT or pull request so we can always keep this module up to date.

=head1 SUPPORT

Bugs may be submitted through L<the RT bug tracker|https://rt.cpan.org/Public/Dist/Display.html?Name=Acme-CPANAuthors-Canadian>
(or L<bug-Acme-CPANAuthors-Canadian@rt.cpan.org|mailto:bug-Acme-CPANAuthors-Canadian@rt.cpan.org>).

I am also usually active on irc, as 'ether' at C<irc.perl.org> and C<irc.libera.chat>.

=head1 AUTHOR

Zoffix Znet <cpan@zoffix.com>

=head1 CONTRIBUTORS

=for stopwords Karen Etheridge Timothy Legge

=over 4

=item *

Karen Etheridge <ether@cpan.org>

=item *

Timothy Legge <timlegge@gmail.com>

=back

=head1 COPYRIGHT AND LICENCE

This software is copyright (c) 2008 by Zoffix Znet <cpan@zoffix.com>.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=cut
